### ISSUE TITLE
Trace can also be 0 or ±p

### ISSUE THREAD

**Issue by defeo** [javad-doliskani/divpoly_pit#9]
Here:

https://github.com/javad-doliskani/divpoly_pit/blob/98734cc4aff5acd423f0d10277c6f9d0162e0eb5/divpoly_pit.tex#L380

t = ±2p is not true in general. It can also be 0 (if j=1728) or ±p (if j=0). That's easy to rule out, but you should be explicit about it (also in Algorithm 2: add a special case for those 2 j-invariants).

**Comment by jake-doliskani** [comment]
Done.

**Comment by defeo** [comment]
You could add somewhere that j=0 is supersingular iff p=2 mod 3, and j=1728 is ...
See also #8.

**Comment by jake-doliskani** [comment]
Added the following in the intro (paragraph 3):
Note that an elliptic curve $E$ with $j(E) = 0$ (resp. $j(E) = 1728$) is supersingular if and only if $p = 2 
\bmod 3$ (resp. $p = 3 \bmod 4$) \cite[Theorem 4.1.c]{silverman2009arithmetic}. Since there is only 
one supersingular curve for $p = 2$ and $p = 3$, which has $j$-invariant $j = 0$, we assume that $p 
> 3$.
